### ISSUE TITLE
PEP8: ambiguous variable name in BIP93 in line python reference

### ISSUE THREAD

**Issue by BenWestgate** [BlockstreamResearch/codex32#63]
These functions from the BIP have PEP8 weak warning: ambiguous variable name: 'l'

```python3
def bech32_lagrange(l, x):
    n = 1
    c = []
    for i in l:
        n = bech32_mul(n, i ^ x)
        m = 1
        for j in l:
            m = bech32_mul(m, (x if i == j else i) ^ j)
        c.append(m)
    return [bech32_mul(n, bech32_inv[i]) for i in c]


def ms32_interpolate(l, x):
    w = bech32_lagrange([s[5] for s in l], x)
    res = []
    for i in range(len(l[0])):
        n = 0
        for j in range(len(l)):
            n ^= bech32_mul(w[j], l[j][i])
        res.append(n)
    return res


def ms32_recover(l):
    return ms32_interpolate(l, 16)
```

Should we change it to something unambiguous or ignore the warning?

Also the in line functions do not have docstrings, should I add docstrings for them to my python reference so it is consistent with the rest of my functions?

**Comment by apoelstra** [comment]
What is ambiguous about it? AFAICS `l` is only used in one way in each function.

**Comment by BenWestgate** [comment]
It's just against the PEP 8 Style Guide I used for format my python reference.
I don't want to change the code I borrowed from the BIP unless it matches but PEP 8 suggests to use 'L' instead of 'l' because of font issues.

[PEP 8 Style Guide: Names to Avoid](https://peps.python.org/pep-0008/#names-to-avoid)

> [Names to Avoid](https://peps.python.org/pep-0008/#names-to-avoid)
> Never use the characters ‘l’ (lowercase letter el), ‘O’ (uppercase letter oh), or ‘I’ (uppercase letter eye) as single character variable names.
> 
> In some fonts, these characters are indistinguishable from the numerals one and zero. When tempted to use ‘l’, use ‘L’ instead.

**Comment by apoelstra** [comment]
Lol. Let's just ignore this. If somebody is using a font that makes it impossible to read code then it's not our responsibility to try to bail them out.
